# Generated by Django 5.0.1 on 2024-03-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('T_id', models.IntegerField(primary_key=True, serialize=False)),
                ('T_name', models.CharField(max_length=300)),
                ('T_description', models.TextField()),
            ],
        ),
    ]
